version: 2
jobs:
  type_check:
    working_directory: /tmp/cpdt
    docker:
      - image: eldesh/coq:8.5pl3
    steps:
      - checkout
      - run:
          shell: /bin/bash --login -eo pipefail
          name: compile 
          command: |
            make

workflows:
  version: 2
  build_doc:
    jobs:
      - type_check

